(() => {
  const key = new URLSearchParams(window.location.search).get("place") || "";
  const guides = {
    "nandi-hills": {
      title:"Nandi Hills", kicker:"The sunrise run", sub:"A pre-dawn ride out of Bengaluru for hill air, sweeping views and a slow breakfast on the way back.",
      distance:"About 60–70 km one way", duration:"Half day", best:"Clear mornings; check forecast", effort:"Easy ride · hill approach",
      intro:"Nandi Hills is the classic early-morning escape from Bengaluru. The ride is as much about leaving the city before traffic builds as it is about the view from the top. Expect the final approach to be slower and busier around popular sunrise hours.",
      route:"Bengaluru → Hebbal / airport corridor → Devanahalli → Nandi Hills approach",
      itinerary:[["Before dawn","Leave with a full tank and check the weather, hill-entry rules and current opening arrangements."],["Approach","Follow the signed approach roads and allow extra time for queues, parking and the final climb."],["At the top","Use designated viewpoints and walkways; avoid leaning over barriers or stopping in the carriageway."],["Return","Come down patiently, then stop for breakfast around the Devanahalli side if convenient."]],
      highlights:["Sunrise and cloud-layer views on suitable days","Historic hilltop setting and walking viewpoints","A practical half-day ride with an early start"],
      cautions:["Hill access, vehicle restrictions, opening times and parking rules can change—check official/local notices before departure.","Fog, wet bends and tourist traffic can reduce visibility; keep a safe following distance."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Sunrise_at_Nandi_Hills.jpg","Sunrise over the hills","https://commons.wikimedia.org/wiki/File:Sunrise_at_Nandi_Hills.jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Nandi_hills_sunrises.jpg","Morning sky above Nandi Hills","https://commons.wikimedia.org/wiki/File:Nandi_hills_sunrises.jpg"]],
      map:"Nandi Hills, Chikkaballapur, Karnataka", nearby:"Devanahalli Fort, Bhoga Nandeeshwara Temple (check opening times), and breakfast stops along the approach."
    },
    "skandagiri": {
      title:"Skandagiri", kicker:"Mist, ridgelines & fort ruins", sub:"A night-before plan and an early ride to the trailhead—this is a trekking day with a motorcycle approach, not a ride to the summit.",
      distance:"About 60–70 km one way", duration:"Half to full day", best:"Cooler months; weather permitting", effort:"Road ride + strenuous trek",
      intro:"Skandagiri, also known as Kalavara Durga, is known for its hilltop fort remains and sunrise treks. The motorcycle takes you to the permitted starting area; the summit is reached on foot. Do not plan the ride around an assumed sunrise entry without checking the current booking and access process.",
      route:"Bengaluru → airport highway corridor → Chikkaballapur → Kalavara village / authorised trailhead",
      itinerary:[["The evening before","Confirm official trek booking, reporting time, permitted route and weather. Pack a headlamp, water and grippy footwear."],["Ride to the trailhead","Start early enough for the booked slot, but follow the actual reporting instructions rather than guessing entry time."],["Trek","Stay with your group and the marked route. Turn back if conditions or fitness make continuing unsafe."],["Return","Rest, hydrate and avoid riding back exhausted; take a food break near Chikkaballapur if needed."]],
      highlights:["Wide views over the surrounding hills when visibility is good","Historic fort ruins along the trekking route","A rewarding ride-and-hike combination"],
      cautions:["Trekking access may require advance booking and can be suspended due to weather or forest rules.","Do not attempt an unauthorised night trek; carry lights, water and suitable footwear."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Cloud_over_Skandagiri_hills.jpg","Clouds over Skandagiri","https://commons.wikimedia.org/wiki/File:Cloud_over_Skandagiri_hills.jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Skandagiri_Hills.jpg","Skandagiri hill landscape","https://commons.wikimedia.org/wiki/File:Skandagiri_Hills.jpg"]],
      map:"Skandagiri trekking starting point, Kalavara, Karnataka", nearby:"Chikkaballapur town and Nandi Hills are in the wider region; treat them as separate stops only if the timing works."
    },
    "savandurga": {
      title:"Savandurga", kicker:"A giant of granite", sub:"A westward ride through the Magadi side of Bengaluru toward a dramatic monolith and forested foothills.",
      distance:"About 50–60 km one way", duration:"Half day for the approach; longer with a trek", best:"Early morning; avoid severe weather", effort:"Easy–moderate road ride; trek can be strenuous",
      intro:"Savandurga is famous for its enormous granite hill landscape. The ride is a good countryside escape, while climbing the hill is a separate activity requiring suitable fitness, footwear and current access information.",
      route:"Bengaluru → Bidadi / Magadi Road → Savandurga foothills and authorised trail access",
      itinerary:[["Start","Leave after checking rain and road conditions, particularly if travelling during the monsoon."],["Ride west","Use the main public road route and slow down through village stretches, junctions and uneven shoulders."],["Explore","Enjoy the landscape from permitted public viewpoints. Trek only if the route is open and you are prepared."],["Return","Refuel and take a break before the city traffic; avoid a rushed descent or late return after a trek."]],
      highlights:["Distinctive granite monolith and rocky landscape","Countryside roads beyond the city edge","Possible pairing with the Manchanabele region when access and time allow"],
      cautions:["Rock surfaces can become dangerously slippery when wet; do not climb in poor weather.","Stay out of restricted forest or dam areas and follow local access instructions."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Savandurga_hill.jpg","Savandurga monolith","https://commons.wikimedia.org/wiki/File:Savandurga_hill.jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Savandurga_hill_top_view.jpg","Views from Savandurga","https://commons.wikimedia.org/wiki/File:Savandurga_hill_top_view.jpg"]],
      map:"Savandurga Hills, Karnataka", nearby:"Manchanabele Reservoir lies in the broader western countryside; do not assume all reservoir viewpoints are open to visitors."
    },
    "manchanabele": {
      title:"Manchanabele Reservoir", kicker:"Water, hills & open country", sub:"A short western escape for a slower ride, broad reservoir views and a countryside feel.",
      distance:"About 40–45 km one way", duration:"2–4 hours", best:"Morning or late afternoon", effort:"Easy road ride",
      intro:"Manchanabele sits in the countryside west of Bengaluru, with water and rocky hills shaping the landscape. Treat this as a scenic ride to permitted public areas rather than a promise of waterside access: boundaries and activities may be restricted.",
      route:"Bengaluru → Magadi Road → local public roads toward Manchanabele",
      itinerary:[["Before leaving","Check recent local access information and weather; do not rely on old social-media directions to private viewpoints."],["The ride","Take the western approach at a relaxed pace and watch for village traffic, farm vehicles and road edges."],["At the destination","Use only clearly permitted public viewpoints. Keep away from dam structures, fenced areas and the water's edge."],["Return","Leave daylight for the return and plan fuel and food before entering quieter stretches."]],
      highlights:["Reservoir landscape framed by low rocky hills","Short ride with a countryside atmosphere","Good companion destination for a wider western loop when access is confirmed"],
      cautions:["Dam/reservoir access, swimming, boating and stopping areas may be prohibited or restricted.","Do not enter water or cross barricades for photographs."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Manchanbele_Dam_02.jpg","Manchanabele Reservoir","https://commons.wikimedia.org/wiki/File:Manchanbele_Dam_02.jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Manchanabele.jpg","View of Manchanabele from the surrounding hills","https://commons.wikimedia.org/wiki/File:Manchanabele.jpg"]],
      map:"Manchanabele Reservoir, Magadi, Karnataka", nearby:"Savandurga foothills and Magadi-side countryside; verify access independently before adding stops."
    },
    "ramanagara": {
      title:"Ramanagara Hills", kicker:"Rock country & craft stops", sub:"A south-west ride through the Mysuru Road corridor, with granite outcrops and the option of a Channapatna craft stop.",
      distance:"About 50–60 km one way", duration:"Half day; longer with stops", best:"Morning", effort:"Easy road ride; climbing is separate",
      intro:"Ramanagara's rocky skyline makes it a recognisable escape from Bengaluru. The town and surrounding hills offer more than one possible stop, so decide whether the day is about the ride, a short heritage/craft visit or a properly planned trek.",
      route:"Bengaluru → Mysuru Road corridor → Ramanagara town → authorised public viewpoints",
      itinerary:[["Start","Check traffic on the Mysuru Road corridor and leave room for slowdowns near towns."],["Ramanagara","Use safe public pull-offs and designated access. Do not stop on the highway shoulder for photographs."],["Optional craft stop","If time allows, continue toward Channapatna for its wooden-toy tradition; check individual shop timings."],["Return","Allow extra time for weekend traffic entering Bengaluru and take a rest stop before the city."]],
      highlights:["Granite formations and distinctive rocky horizons","A route with food and town-stop options","Optional Channapatna wooden-toy shopping"],
      cautions:["Climbing routes and hill access are not the same as the public road destination; check permissions and conditions.","Never park on fast highway shoulders or enter private land for a viewpoint."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Ramanagara_Hills_%2810306067976%29.jpg","Ramanagara Hills","https://commons.wikimedia.org/wiki/File:Ramanagara_Hills_(10306067976).jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Savandurga_hill.jpg","Granite hill landscape in the wider region","https://commons.wikimedia.org/wiki/File:Savandurga_hill.jpg"]],
      map:"Ramanagara Hills, Karnataka", nearby:"Channapatna for wooden toys and Ramanagara town for food and essentials."
    },
    "hesaraghatta": {
      title:"Hesaraghatta Lake", kicker:"Open skies on the city's edge", sub:"A quieter north-western ride for wide horizons, grassland and birdlife—best enjoyed with a light footprint.",
      distance:"Short ride; varies by starting point", duration:"2–4 hours", best:"Early morning or late afternoon", effort:"Easy road ride",
      intro:"Hesaraghatta offers a different kind of escape: open land and big skies rather than a steep climb. Water levels and the look of the landscape change seasonally, and parts of the area are ecologically sensitive.",
      route:"Bengaluru → north-western city roads → Hesaraghatta Lake / permitted public access",
      itinerary:[["Choose a time","Early morning or late afternoon usually gives softer light; check weather before setting out."],["Ride out","Expect urban-edge traffic before the road opens up. Follow posted restrictions and avoid speeding through villages."],["Explore gently","Stay on public roads and established paths. Watch birds from a distance and leave vegetation undisturbed."],["Return","Do not count on facilities at the lake edge; carry water and plan refreshments before leaving the city."]],
      highlights:["Wide grassland and open-sky views","Seasonal birdwatching opportunities","A compact escape without a long highway day"],
      cautions:["Lake and grassland access may be limited; stay outside fenced or protected areas.","Avoid disturbing birds, littering or riding off-road across grassland."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Hessarghatta_Lake_%2850935033071%29.jpg","Hesaraghatta Lake in mist","https://commons.wikimedia.org/wiki/File:Hessarghatta_Lake_(50935033071).jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Hessarghatta_Lake_%2850935033881%29.jpg","Hesaraghatta Lake landscape","https://commons.wikimedia.org/wiki/File:Hessarghatta_Lake_(50935033881).jpg"]],
      map:"Hesaraghatta Lake, Bengaluru, Karnataka", nearby:"North-west Bengaluru for food and fuel; confirm any nature-area access before detouring."
    },
    "devanahalli": {
      title:"Devanahalli Fort & Countryside", kicker:"History north of the city", sub:"A manageable northern ride that pairs rural stretches with the historic fort near Bengaluru's airport corridor.",
      distance:"About 30–40 km one way", duration:"Half day", best:"Morning", effort:"Easy road ride",
      intro:"Devanahalli works well when you want a shorter ride with a heritage stop rather than a remote destination. The airport corridor can be busy, so choose your route and timing with traffic in mind.",
      route:"Bengaluru → Yelahanka / airport corridor → Devanahalli town → Fort",
      itinerary:[["Start","Check traffic around the airport road and use legal, well-marked crossings and turns."],["Arrive in town","Park only where permitted and walk into the heritage area rather than riding through crowded lanes."],["Explore the fort","Respect monument rules, local worship and any restricted or closed sections."],["Return","Add a meal stop in town if useful, then plan around the return traffic."]],
      highlights:["Historic fort walls and local heritage","A shorter ride than the hill and river destinations","Easy to combine with a relaxed town visit"],
      cautions:["Monument access and opening arrangements may change; check locally before travelling.","Avoid stopping on airport access roads or photographing restricted security areas."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/Devanahalli_Fort.jpg","Devanahalli Fort","https://commons.wikimedia.org/wiki/File:Devanahalli_Fort.jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Devanahalli_fort%2C_near_Bangalore.JPG","Fort walls near Bengaluru","https://commons.wikimedia.org/wiki/File:Devanahalli_fort,_near_Bangalore.JPG"]],
      map:"Devanahalli Fort, Devanahalli, Karnataka", nearby:"Devanahalli town for food and essentials; Bhoga Nandeeshwara Temple is a separate nearby heritage option if time permits."
    },
    "mekedatu-sangama": {
      title:"Sangama & Mekedatu", kicker:"The full-day Cauvery run", sub:"A longer ride south of Bengaluru toward the confluence and river gorge—plan around access rules, daylight and changing river conditions.",
      distance:"Around 90–100 km one way, depending on endpoint", duration:"Full day", best:"Start early; check seasonal conditions", effort:"Long day ride",
      intro:"Sangama is where the Arkavathi meets the Cauvery; Mekedatu is the narrow rocky gorge farther along the river. This is a full-day outing, not a quick photo stop. Road access, the final approach and local transport arrangements can vary, so confirm the current setup before leaving.",
      route:"Bengaluru → Kanakapura Road → Kanakapura → Sangama / authorised Mekedatu access",
      itinerary:[["Before departure","Check current forest, river and destination access notices; start with a full tank and enough daylight."],["Ride to Kanakapura","Take breaks, hydrate and ride defensively on rural stretches."],["Sangama / Mekedatu","Follow the current official visitor route and instructions. Do not enter the river, climb wet rocks or cross barriers."],["Return","Leave well before dark, especially if access queues or local transport extend the day. Avoid riding tired."]],
      highlights:["Cauvery and Arkavathi river landscape","Rocky gorge scenery and forested surroundings","A rewarding long ride when access and weather are suitable"],
      cautions:["River levels and currents can be dangerous even when the surface looks calm; never enter the water or approach slippery edges.","Forest gates, visitor access, local transport and timings may change. Verify on the day and obey closures."],
      photos:[["https://commons.wikimedia.org/wiki/Special:Redirect/file/River_Cauvery_in_Mekadatu%2C_Karnataka.jpg","Cauvery river through the Mekedatu gorge","https://commons.wikimedia.org/wiki/File:River_Cauvery_in_Mekadatu,_Karnataka.jpg"],["https://commons.wikimedia.org/wiki/Special:Redirect/file/Mekedatu_in_summer_2012.jpg","Mekedatu in the dry season","https://commons.wikimedia.org/wiki/File:Mekedatu_in_summer_2012.jpg"]],
      map:"Sangama, Kanakapura, Karnataka", nearby:"Kanakapura for food and fuel; do not add remote stops unless time, daylight and current access rules allow."
    }
  };

  const guide = guides[key];
  if (!guide) return;
  const app = document.getElementById("app");
  if (!app) return;
  const esc = value => String(value).replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
  const mapsQuery = encodeURIComponent(guide.map);
  const directions = "https://www.google.com/maps/dir/?api=1&origin=" + encodeURIComponent("Bengaluru, Karnataka") + "&destination=" + encodeURIComponent(guide.map) + "&travelmode=driving";
  const images = guide.photos.map((photo, i) => '<figure class="blr-photo"><img src="' + esc(photo[0]) + '" alt="' + esc(photo[1]) + '" loading="lazy" decoding="async"><figcaption>' + esc(photo[1]) + ' · <a href="' + esc(photo[2]) + '" target="_blank" rel="noopener noreferrer">Photo & licence</a></figcaption></figure>').join("");
  const itinerary = guide.itinerary.map((item, i) => '<li class="blr-timeline-item"><span class="blr-step">' + String(i+1).padStart(2,"0") + '</span><div><h3>' + esc(item[0]) + '</h3><p>' + esc(item[1]) + '</p></div></li>').join("");
  const highlights = guide.highlights.map(item => "<li>" + esc(item) + "</li>").join("");
  const cautions = guide.cautions.map(item => "<li>" + esc(item) + "</li>").join("");
  const pageTitle = "HiddenRides Bengaluru — " + guide.title + " ride guide";
  document.title = pageTitle;
  const meta = document.querySelector('meta[name="description"]');
  if (meta) meta.content = guide.sub + " Route, ride plan, photos and safety notes from HiddenRides.";
  const canonical = document.querySelector('link[rel="canonical"]');
  if (canonical) canonical.href = "https://hiddenrides.com/ride.html?place=" + key;
  const css = document.createElement("style");
  css.id = "bengaluru-adventure-guide-styles";
  css.textContent = `
    .blr-page{--blr-ink:#151916;--blr-muted:#626a63;--blr-line:#e2e6de;--blr-accent:#b7df00;color:var(--blr-ink);padding-bottom:52px}
    .blr-crumb{font-size:12px;color:#667064;margin:12px 0 20px;display:flex;gap:8px;flex-wrap:wrap}.blr-crumb a{text-decoration:underline;text-underline-offset:3px}
    .blr-hero{position:relative;min-height:390px;border-radius:26px;overflow:hidden;background:#202a21;display:flex;align-items:flex-end;margin-bottom:22px}
    .blr-hero>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}
    .blr-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(8,12,9,.84),rgba(8,12,9,.42) 62%,rgba(8,12,9,.05)),linear-gradient(0deg,rgba(8,12,9,.58),transparent 65%)}
    .blr-hero-copy{position:relative;z-index:1;padding:clamp(24px,5vw,54px);max-width:790px;color:#fff}.blr-kicker{font-size:11px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:#d9ff54}
    .blr-hero h1{font-size:clamp(38px,7vw,76px);line-height:.96;letter-spacing:-.055em;margin:14px 0;color:#fff}.blr-hero p{font-size:clamp(15px,2vw,18px);line-height:1.65;color:#f1f3ed;max-width:650px}
    .blr-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.blr-btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;border-radius:999px;padding:12px 17px;font-size:12px;font-weight:850;background:var(--blr-accent);color:#11150d;text-decoration:none}.blr-btn.alt{background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.55);color:#fff;backdrop-filter:blur(8px)}
    .blr-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:18px 0 42px}.blr-stat{border:1px solid var(--blr-line);border-radius:15px;padding:16px;background:#f8f9f6;min-width:0}.blr-stat small{display:block;color:#687065;font-size:10px;text-transform:uppercase;font-weight:850;letter-spacing:.08em;margin-bottom:8px}.blr-stat strong{font-size:13px;line-height:1.4;display:block}
    .blr-section{margin:42px 0}.blr-section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:18px}.blr-section h2{font-size:clamp(25px,4vw,38px);letter-spacing:-.04em;margin:0 0 9px;color:#171b17}.blr-section-head p,.blr-lede{color:var(--blr-muted);line-height:1.7;margin:0;max-width:740px;font-size:14px}
    .blr-gallery{display:grid;grid-template-columns:1.15fr 1fr;gap:14px}.blr-photo{margin:0;border:1px solid var(--blr-line);border-radius:18px;overflow:hidden;background:#f4f6f1;min-width:0}.blr-photo img{display:block;width:100%;height:280px;object-fit:cover;background:#e7eae2}.blr-photo:first-child{grid-row:span 2}.blr-photo:first-child img{height:100%;min-height:574px}.blr-photo figcaption{font-size:11px;line-height:1.5;padding:11px 13px;color:#596256}.blr-photo figcaption a{color:#425a0a;text-decoration:underline;text-underline-offset:2px}
    .blr-two-col{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(0,.85fr);gap:18px;align-items:start}.blr-panel{border:1px solid var(--blr-line);border-radius:20px;padding:clamp(18px,3vw,28px);background:#f8f9f6;min-width:0}.blr-panel h2{font-size:25px;letter-spacing:-.035em;margin:0 0 12px}.blr-panel p{font-size:14px;line-height:1.75;color:#51594f}.blr-bullets{padding-left:20px;margin:12px 0 0}.blr-bullets li{padding:0 0 10px 3px;color:#3f473d;font-size:13px;line-height:1.65}
    .blr-timeline{list-style:none;padding:0;margin:0;display:grid;gap:0}.blr-timeline-item{display:grid;grid-template-columns:44px 1fr;gap:12px;padding:16px 0;border-bottom:1px solid var(--blr-line)}.blr-timeline-item:last-child{border-bottom:0}.blr-step{display:grid;place-items:center;border-radius:50%;width:38px;height:38px;background:#e9f4c7;color:#30420b;font-weight:900;font-size:11px}.blr-timeline-item h3{margin:2px 0 6px;font-size:15px}.blr-timeline-item p{margin:0;color:#586054;font-size:13px;line-height:1.65}
    .blr-map-wrap{border:1px solid var(--blr-line);border-radius:20px;overflow:hidden;background:#f4f6f1}.blr-map-wrap iframe{display:block;width:100%;height:360px;border:0}.blr-map-foot{padding:15px 18px;display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.blr-map-foot p{margin:0;font-size:12px;line-height:1.6;color:#5d6659}
    .blr-warning{border-left:4px solid #b7df00;background:#f5f8eb;border-radius:0 15px 15px 0;padding:18px 20px;margin:20px 0}.blr-warning strong{display:block;margin-bottom:6px}.blr-warning p{font-size:13px;line-height:1.7;color:#50594a;margin:0}
    .blr-bottom-nav{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;border-top:1px solid var(--blr-line);padding-top:24px;margin-top:44px}.blr-bottom-nav a{font-size:13px;font-weight:800;text-decoration:underline;text-underline-offset:4px}
    .blr-photo.is-failed{display:none}
    @media(max-width:720px){.blr-hero{min-height:430px;border-radius:20px}.blr-hero:after{background:linear-gradient(0deg,rgba(8,12,9,.86),rgba(8,12,9,.1) 95%)}.blr-stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-bottom:32px}.blr-stat{padding:13px}.blr-two-col{grid-template-columns:1fr}.blr-gallery{grid-template-columns:1fr 1fr;gap:9px}.blr-photo:first-child{grid-column:1/-1;grid-row:auto}.blr-photo:first-child img{height:250px;min-height:0}.blr-photo img{height:145px}.blr-photo figcaption{font-size:10px;padding:9px}.blr-section{margin:32px 0}.blr-section-head{display:block}.blr-map-wrap iframe{height:300px}.blr-hero h1{letter-spacing:-.04em}}
    @media(max-width:380px){.blr-hero{min-height:400px}.blr-stats{grid-template-columns:1fr 1fr}.blr-stat strong{font-size:12px}.blr-gallery{grid-template-columns:1fr}.blr-photo:first-child{grid-column:auto}.blr-photo img,.blr-photo:first-child img{height:210px;min-height:0}.blr-map-wrap iframe{height:260px}}
  `;
  document.head.appendChild(css);
  app.innerHTML = '<div class="blr-page"><div class="blr-crumb"><a href="/">Home</a><span>›</span><a href="bengaluru.html">Bengaluru rides</a><span>›</span><span>' + esc(guide.title) + '</span></div>' +
    '<section class="blr-hero"><img src="' + esc("https://commons.wikimedia.org/wiki/Special:Redirect/file/" + ({"nandi-hills":"Nandi_Hills%2C_Bengaluru.jpg","skandagiri":"Skandagiri_Hills.jpg","savandurga":"Savandurga_hill.jpg","manchanabele":"Manchanbele_Dam_01.jpg","ramanagara":"Ramanagara_Hills_%2810306067976%29.jpg","hesaraghatta":"Hessarghatta_Lake_%2850935033071%29.jpg","devanahalli":"Devanahalli_Fort.jpg","mekedatu-sangama":"River_Cauvery_in_Mekadatu%2C_Karnataka.jpg"}[key])) + '" alt="' + esc(guide.title + " landscape") + '" fetchpriority="high"><div class="blr-hero-copy"><div class="blr-kicker">HiddenRides field guide · Bengaluru</div><h1>' + esc(guide.title) + '</h1><p>' + esc(guide.sub) + '</p><div class="blr-actions"><a class="blr-btn" href="' + esc(directions) + '" target="_blank" rel="noopener">Get directions ↗</a><a class="blr-btn alt" href="#blr-route">Explore route & map ↓</a></div></div></section>' +
    '<section class="blr-stats" aria-label="Ride details"><div class="blr-stat"><small>Distance</small><strong>' + esc(guide.distance) + '</strong></div><div class="blr-stat"><small>Time needed</small><strong>' + esc(guide.duration) + '</strong></div><div class="blr-stat"><small>Best conditions</small><strong>' + esc(guide.best) + '</strong></div><div class="blr-stat"><small>Ride type</small><strong>' + esc(guide.effort) + '</strong></div></section>' +
    '<section class="blr-section"><div class="blr-section-head"><div><h2>The landscape</h2><p>Photos and views from the destination. Select “Photo & licence” to view each original Commons file and its reuse terms.</p></div></div><div class="blr-gallery">' + images + '</div></section>' +
    '<section class="blr-section blr-two-col"><article class="blr-panel"><h2>Why make this ride?</h2><p>' + esc(guide.intro) + '</p><h3>What to look forward to</h3><ul class="blr-bullets">' + highlights + '</ul></article><article class="blr-panel"><h2>Route at a glance</h2><p>' + esc(guide.route) + '</p><ul class="blr-bullets"><li>Distances are indicative from Bengaluru and vary by starting point and exact route.</li><li>Use navigation for current traffic and road closures; this guide is not live routing.</li><li>Fuel, food and mobile signal may be less predictable outside the city.</li></ul></article></section>' +
    '<section class="blr-section" id="blr-route"><div class="blr-section-head"><div><h2>Plan the ride</h2><p>A practical sequence to help you plan the day without treating estimates as guaranteed timings.</p></div></div><div class="blr-two-col"><article class="blr-panel"><ol class="blr-timeline">' + itinerary + '</ol></article><div class="blr-panel"><h2>Map & navigation</h2><p>Use the embedded map for location context, then open Google Maps for current directions from Bengaluru.</p><div class="blr-map-wrap"><iframe title="Map of ' + esc(guide.title) + '" src="https://www.google.com/maps?q=' + mapsQuery + '&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><div class="blr-map-foot"><p>Map preview · check live navigation before departure.</p><a class="blr-btn" href="' + esc(directions) + '" target="_blank" rel="noopener">Open directions ↗</a></div></div></div></div></section>' +
    '<section class="blr-section blr-two-col"><article class="blr-panel"><h2>Nearby ideas</h2><p>' + esc(guide.nearby) + '</p><p>Keep extra stops optional: traffic, weather, access restrictions and daylight should decide the final plan.</p><a class="blr-btn" href="bengaluru.html">Explore all Bengaluru rides</a></article><article class="blr-panel"><h2>Safety & access notes</h2><ul class="blr-bullets">' + cautions + '<li>Wear a certified helmet and protective gear; check tyres, brakes, fuel and weather before departure.</li><li>Do not ride tired, speed through villages, litter or enter closed/private areas.</li></ul></article></section>' +
    '<div class="blr-warning"><strong>Before you leave</strong><p>Opening hours, trekking permits, forest and reservoir access, road conditions and river safety can change. Confirm current local or official instructions before riding. HiddenRides does not represent these estimates as live-verified conditions.</p></div>' +
    '<div class="blr-bottom-nav"><a href="bengaluru.html">← All Bengaluru rides</a><a href="ride.html?place=' + esc(key) + '">Refresh this guide ↗</a></div></div>';
  app.querySelectorAll(".blr-photo img,.blr-hero img").forEach(img => {
    img.addEventListener("error", function(){ if(this.closest(".blr-photo")) this.closest(".blr-photo").classList.add("is-failed"); else { this.style.display="none"; const hero=this.closest(".blr-hero"); if(hero) hero.style.background="linear-gradient(135deg,#25382b,#101810)"; } }, {once:true});
  });
})();